# MCFI 配置 v2.6.14（编辑后重启应用生效；面板 http://127.0.0.1:4400 或按冲突顺延）
enabled=1
target_mode=1
targets=com.tencent.tmgp.sgame=gles,com.miHoYo.hkrpg=vulkan,com.ss.android.ugc.aweme=video
interp_mode=0
video_interp_mode=1
strength=60
smooth=60
game_interval=1
video_interval=1
me_quality=60
panel_port=4400
log_level=0
vk_mci=1
pts_align_gles=0
pts_align_vk=1
me_mv16=0
vsync_hz=0
