# MCFI 配置（版本见 module.prop；编辑后重启应用生效；面板 http://127.0.0.1:4400 或按冲突顺延）
enabled=1
target_mode=1
targets=com.tencent.tmgp.sgame=gles,com.miHoYo.hkrpg=vulkan,com.ss.android.ugc.aweme=video
interp_mode=0
strength=60
smooth=60
game_interval=1
video_interval=1
me_quality=60
panel_port=4400
log_level=1
vk_mci=1
gles_pts_enable=0
vk_pts_enable=1
video_interp_mode=1
